In [1]:
import numpy as np

a = np.arange(6).reshape(3, 2)
print("a行列")
print(a)

b = np.arange(8).reshape(2, 4)
print("b行列")
print(b)

product = np.dot(a, b)
print("a,bの行列積")
product

a行列
[[0 1]
 [2 3]
 [4 5]]
b行列
[[0 1 2 3]
 [4 5 6 7]]
a,bの行列積


array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [2]:
product.max()

47